name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
        - image:    'ubuntu-latest'
          host:     'linux'
          dirsep:   ':'
        - image:    'windows-latest'
          host:     'windows'
          dirsep:   ';'

    runs-on: ${{ matrix.image }}

    steps:
    - uses: actions/checkout@v4
    - name: Open Watcom setup
      uses: open-watcom/setup-watcom@v0
      with:
        version: "2.0"
    - name: Create build directories
      run: |
        mkdir bin
        mkdir lib
        mkdir include
      shell: bash
    - name: Open Zinc library
      run: |
        echo "$INCLUDE"
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h
        echo "$INCLUDE"
        wmake -f ow20.mak -h dos32
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/win
        echo "$INCLUDE"
        wmake -f ow20.mak -h windows
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/nt
        wmake -f ow20.mak -h winnt
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/nt
        wmake -f ow20.mak -h win32
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/os2
        wmake -f ow20.mak -h os2
      shell: bash
      working-directory: source
    - name: Open Zinc Designer Libraries
      run: |
        echo "$INCLUDE"
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$OZINCPATH
        echo "$INCLUDE"
        wmake -f ow20.mak -h make_dos32_modules
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/win${{ matrix.dirsep }}$OZINCPATH
        echo "$INCLUDE"
        wmake -f ow20.mak -h make_windows_modules
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/nt${{ matrix.dirsep }}$OZINCPATH
        wmake -f ow20.mak -h make_winnt_modules
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/nt${{ matrix.dirsep }}$OZINCPATH
        wmake -f ow20.mak -h make_win32_modules
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/os2${{ matrix.dirsep }}$OZINCPATH
        wmake -f ow20.mak -h make_os2_modules
      shell: bash
      working-directory: design
      env:
        OZINCPATH: ${{ github.workspace }}/include
        LIB: .${{ matrix.dirsep }}${{ github.workspace }}/lib/ow20
    - name: Open Zinc Designer Executable
      run: |
        echo "$INCLUDE"
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h:$OZINCPATH
        echo "$INCLUDE"
        wmake -f ow20.mak -h dos32
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/win${{ matrix.dirsep }}$OZINCPATH
        echo "$INCLUDE"
        wmake -f ow20.mak -h windows
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/nt${{ matrix.dirsep }}$OZINCPATH
        wmake -f ow20.mak -h winnt
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/nt${{ matrix.dirsep }}$OZINCPATH
        wmake -f ow20.mak -h win32
        export INCLUDE=.${{ matrix.dirsep }}$WATCOM/h${{ matrix.dirsep }}$WATCOM/h/os2${{ matrix.dirsep }}$OZINCPATH
        wmake -f ow20.mak -h os2
      shell: bash
      working-directory: design
      env:
        OZINCPATH: ${{ github.workspace }}/include
        LIB: .${{ matrix.dirsep }}${{ github.workspace }}/lib/ow20
        DIRSEP: ${{ matrix.dirsep }}
