name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build1:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Open Watcom setup
      uses: open-watcom/setup-watcom@v0
      with:
        version: "2.0"
    - name: Create build directories
      run: |
        mkdir bin
        mkdir lib
        mkdir include
    - name: Open Zinc library
      run: |
        setlocal
        @set INCLUDE=.;%WATCOM%\H
        wmake -f ow20.mak -h dos32
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\WIN
        wmake -f ow20.mak -h windows
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\NT
        wmake -f ow20.mak -h winnt
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\NT
        wmake -f ow20.mak -h win32
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\OS2
        wmake -f ow20.mak -h os2
        endlocal
      shell: cmd
      working-directory: source
    - name: Open Zinc Designer Libraries
      run: |
        setlocal
        @set INCLUDE=.;%WATCOM%\H;%OZINCPATH%
        wmake -f ow20.mak -h make_dos32_modules
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\WIN;%OZINCPATH%
        wmake -f ow20.mak -h make_windows_modules
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\NT;%OZINCPATH%
        wmake -f ow20.mak -h make_winnt_modules
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\NT;%OZINCPATH%
        wmake -f ow20.mak -h make_win32_modules
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\OS2;%OZINCPATH%
        wmake -f ow20.mak -h make_os2_modules
        endlocal
      shell: cmd
      working-directory: design
      env:
        OZINCPATH: ${{ github.workspace }}\include
        LIB: .;${{ github.workspace }}\lib\ow20
    - name: Open Zinc Designer Executable
      run: |
        setlocal
        @set INCLUDE=.;%WATCOM%\H;%OZINCPATH%
        wmake -f ow20.mak -h dos32
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\WIN;%OZINCPATH%
        wmake -f ow20.mak -h windows
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\NT;%OZINCPATH%
        wmake -f ow20.mak -h winnt
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\NT;%OZINCPATH%
        wmake -f ow20.mak -h win32
        @set INCLUDE=.;%WATCOM%\H;%WATCOM%\H\OS2;%OZINCPATH%
        wmake -f ow20.mak -h os2
        endlocal
      shell: cmd
      working-directory: design
      env:
        OZINCPATH: ${{ github.workspace }}\include
        LIB: .;${{ github.workspace }}\lib\ow20

  build2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Open Watcom setup
      uses: open-watcom/setup-watcom@v0
      with:
        version: "2.0"
    - name: Create build directories
      run: |
        mkdir bin
        mkdir lib
        mkdir include
      shell: bash
    - name: Open Zinc library
      run: |
        @export INCLUDE=.:$WATCOM/h
        wmake -f ow20.mak -h dos32
        @export INCLUDE=.:$WATCOM/h:$WATCOM/h/win
        wmake -f ow20.mak -h windows
        @export INCLUDE=.:$WATCOM/h:$WATCOM/h/nt
        wmake -f ow20.mak -h winnt
        @export INCLUDE=.:$WATCOM/h:$WATCOM/h/nt
        wmake -f ow20.mak -h win32
        @export INCLUDE=.:$WATCOM/h:$WATCOM/h/os2
        wmake -f ow20.mak -h os2
      shell: bash
      working-directory: source
    - name: Open Zinc Designer Libraries
      run: |
        @set INCLUDE=.:$WATCOM/h:$OZINCPATH
        wmake -f ow20.mak -h make_dos32_modules
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/win:$OZINCPATH
        wmake -f ow20.mak -h make_windows_modules
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/nt:$OZINCPATH
        wmake -f ow20.mak -h make_winnt_modules
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/nt:$OZINCPATH
        wmake -f ow20.mak -h make_win32_modules
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/os2:$OZINCPATH
        wmake -f ow20.mak -h make_os2_modules
      shell: bash
      working-directory: design
      env:
        OZINCPATH: ${{ github.workspace }}/include
        LIB: .:${{ github.workspace }}/lib/ow20
    - name: Open Zinc Designer Executable
      run: |
        @set INCLUDE=.:$WATCOM/h:$OZINCPATH
        wmake -f ow20.mak -h dos32
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/win:$OZINCPATH
        wmake -f ow20.mak -h windows
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/nt:$OZINCPATH
        wmake -f ow20.mak -h winnt
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/nt:$OZINCPATH
        wmake -f ow20.mak -h win32
        @set INCLUDE=.:$WATCOM/h:$WATCOM/h/os2:$OZINCPATH
        wmake -f ow20.mak -h os2
      shell: bash
      working-directory: design
      env:
        OZINCPATH: ${{ github.workspace }}/include
        LIB: .:${{ github.workspace }}/lib/ow20

